name: Auto Update
on:
  schedule:
    - cron:  "0 8 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
    - uses: actions/checkout@v4.2.2
      
    - name: Run a one-line script
      run: bash ./host.sh
      
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.1.0
      with:
           commit_message: Auto Update
           branch: master
           commit_options: '--no-verify --signoff'
           repository: .
           commit_user_name: github-actions
           commit_user_email: github-actions@github.com
           push_options: '--force'
